services:
  - type: web
    name: paper-trading
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: bash -lc "python manage.py migrate --noinput && gunicorn config.wsgi"
    envVars:
      - key: SECRET_KEY
        fromSecret: SECRET_KEY
      - key: DEBUG
        fromSecret: DEBUG
    autoDeploy: true
