# Generated by Django 6.0.7 on 2026-07-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='created_at',
            new_name='entry_date',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='price',
            new_name='entry_price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='trade_type',
        ),
        migrations.AddField(
            model_name='trade',
            name='exit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10),
        ),
    ]
