# Generated by Django 6.0.7 on 2026-07-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_rename_created_at_trade_entry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='entry_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='entry_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='exit_date',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='exit_price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='status',
        ),
        migrations.AddField(
            model_name='trade',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4),
            preserve_default=False,
        ),
    ]
