# Generated by Django 6.0.7 on 2026-07-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=15),
        ),
    ]
