# Generated by Django 6.0.7 on 2026-07-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signal',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signal',
            name='trend',
            field=models.CharField(default='Sideways', max_length=20),
        ),
        migrations.AlterField(
            model_name='signal',
            name='signal',
            field=models.CharField(choices=[('STRONG BUY', 'STRONG BUY'), ('BUY', 'BUY'), ('WATCH', 'WATCH'), ('HOLD', 'HOLD'), ('AVOID', 'AVOID')], default='HOLD', max_length=20),
        ),
    ]
