# Generated by Django 6.0.7 on 2026-07-24 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_signal_confidence_signal_reason_signal_score_and_more'),
        ('stocks', '0002_stock_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signal',
            options={'ordering': ['-score', '-created_at'], 'verbose_name': 'Signal', 'verbose_name_plural': 'Signals'},
        ),
        migrations.AddField(
            model_name='signal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='confidence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='signal',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='signal',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='signal',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal', to='stocks.stock'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='trend',
            field=models.CharField(choices=[('Bullish', 'Bullish'), ('Bearish', 'Bearish'), ('Sideways', 'Sideways')], default='Sideways', max_length=20),
        ),
    ]
