# Generated by Django 6.0.7 on 2026-07-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_alter_signal_options_signal_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='signal',
            name='ema20',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='signal',
            name='ema200',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='signal',
            name='ema50',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='signal',
            name='ema_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signal',
            name='rr_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signal',
            name='rsi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='signal',
            name='rsi_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signal',
            name='trend_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signal',
            name='volume',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signal',
            name='volume_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
