# Generated by Django 6.0.7 on 2026-07-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('exchange', models.CharField(max_length=10)),
            ],
        ),
    ]
