# Generated by Django 6.0.7 on 2026-07-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stockmaster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmaster',
            options={'ordering': ['symbol']},
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockmaster',
            name='exchange',
            field=models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], default='NSE', max_length=10),
        ),
    ]
